INSERT INTO tables (NUMBER,ORDERS_ID) VALUES (1,2);
INSERT INTO tables (NUMBER,ORDERS_ID) VALUES (2,4);
INSERT INTO tables (NUMBER,ORDERS_ID) VALUES (3,7);
INSERT INTO tables (NUMBER,ORDERS_ID) VALUES (4,9);