INSERT INTO checkout (PAYMENT_TYPE,ORDERS_ID) VALUES ('VISA CARD',1);
INSERT INTO checkout (PAYMENT_TYPE,ORDERS_ID) VALUES ('MASTERCARD',2);
INSERT INTO checkout (PAYMENT_TYPE,ORDERS_ID) VALUES ('CASH',3);
INSERT INTO checkout (PAYMENT_TYPE,ORDERS_ID) VALUES ('AMEX CARD',4);