INSERT INTO checkout (ORDER_ID,PAYMENT_TYPE) VALUES ('1','VISA CARD');
INSERT INTO checkout (ORDER_ID,PAYMENT_TYPE) VALUES ('2','MASTERCARD');
INSERT INTO checkout (ORDER_ID,PAYMENT_TYPE) VALUES ('3','CASH');
INSERT INTO checkout (ORDER_ID,PAYMENT_TYPE) VALUES ('4','AMEX CARD');


